# Generated by Django 4.2.1 on 2023-07-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpayment',
            options={'verbose_name': 'Order Payment', 'verbose_name_plural': 'Order Payments'},
        ),
        migrations.AlterModelOptions(
            name='purchasepayment',
            options={'verbose_name': 'Purchase Payment', 'verbose_name_plural': 'Purchase Payments'},
        ),
    ]
