# Generated by Django 4.1.3 on 2023-05-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_price_orderdetail_price_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='price',
            new_name='price_box',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='price_currency',
            new_name='price_box_currency',
        ),
    ]
