# Generated by Django 4.1.3 on 2023-05-16 12:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_rename_price_purchasedetail_price_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='base_discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='discount_shop',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
