# Generated by Django 4.1.3 on 2023-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
    ]
