# Generated by Django 4.1.3 on 2023-05-09 04:07

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_novat_box',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=Decimal('0'), default_currency='VND', help_text='This is the price excluding VAT of the product sold in the box.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_novat_pcs',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=Decimal('0'), default_currency='VND', help_text='This is the price excluding VAT of the product sold by quantity.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=Decimal('0'), default_currency='VND', help_text='This is the price of the imported product.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price_vat',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=Decimal('0'), default_currency='VND', help_text='This is the price vat of the imported product.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_price_vat_box',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=Decimal('0'), default_currency='VND', help_text='This is the price VAT of the product sold in the box.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_price_vat_pcs',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=Decimal('0'), default_currency='VND', help_text='This is the price VAT of the product sold by quantity.', max_digits=14, null=True),
        ),
    ]
