# Generated by Django 4.1.3 on 2023-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Waiting', 'Shipping'), ('Done', 'Done'), ('Shipping', 'Waiting')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('motobike', 'MOTOBIKE'), ('car', 'CAR'), ('truck', 'TRUCK')], default='CAR', max_length=50),
        ),
    ]
