# Generated by Django 4.1.3 on 2023-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_delivery_status_alter_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Shipping', 'Waiting'), ('Done', 'Done'), ('Waiting', 'Shipping')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('truck', 'TRUCK'), ('car', 'CAR'), ('motobike', 'MOTOBIKE')], default='CAR', max_length=50),
        ),
    ]
