# Generated by Django 4.1.3 on 2023-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_delivery_code_alter_delivery_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Shipping', 'Waiting'), ('Waiting', 'Shipping'), ('Done', 'Done')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('motobike', 'MOTOBIKE'), ('car', 'CAR'), ('truck', 'TRUCK')], default='CAR', max_length=50),
        ),
    ]
