# Generated by Django 4.1.3 on 2023-05-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Waiting', 'Shipping'), ('Shipping', 'Waiting'), ('Done', 'Done')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('car', 'CAR'), ('truck', 'TRUCK'), ('motobike', 'MOTOBIKE')], default='CAR', max_length=50),
        ),
    ]
