# Generated by Django 4.1.3 on 2023-05-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_alter_delivery_delivery_status_alter_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Shipping', 'Waiting'), ('Waiting', 'Shipping'), ('Done', 'Done')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('truck', 'TRUCK'), ('car', 'CAR'), ('motobike', 'MOTOBIKE')], default='CAR', max_length=50),
        ),
    ]
