# Generated by Django 4.1.3 on 2023-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Waiting', 'Shipping'), ('Done', 'Done'), ('Shipping', 'Waiting')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('truck', 'TRUCK'), ('car', 'CAR'), ('motobike', 'MOTOBIKE')], default='CAR', max_length=50),
        ),
    ]
