# Generated by Django 4.1.3 on 2023-05-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_alter_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Waiting', 'Shipping'), ('Done', 'Done'), ('Shipping', 'Waiting')], default='Waiting', max_length=50),
        ),
    ]
