# Generated by Django 4.1.3 on 2023-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Shipping', 'Waiting'), ('Waiting', 'Shipping')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('motobike', 'MOTOBIKE'), ('car', 'CAR'), ('truck', 'TRUCK')], default='CAR', max_length=50),
        ),
    ]
