# Generated by Django 4.1.3 on 2023-05-15 15:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='delivery',
            managers=[
                ('company_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='status',
            managers=[
                ('company_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transport',
            managers=[
                ('company_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Waiting', 'Shipping'), ('Shipping', 'Waiting'), ('Done', 'Done')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('car', 'CAR'), ('motobike', 'MOTOBIKE'), ('truck', 'TRUCK')], default='CAR', max_length=50),
        ),
    ]
