# Generated by Django 4.1.3 on 2023-05-16 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_order_managers_alter_purchase_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0021_alter_delivery_managers_alter_status_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Waiting', 'Shipping'), ('Shipping', 'Waiting')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_order_related', to='transaction.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_shipper_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_delivery_related', to='delivery.delivery'),
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_status_related', to='delivery.status'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_shipper_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('motobike', 'MOTOBIKE'), ('truck', 'TRUCK'), ('car', 'CAR')], default='CAR', max_length=50),
        ),
    ]
