# Generated by Django 4.1.3 on 2023-05-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_alter_delivery_delivery_status_alter_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Shipping', 'Waiting'), ('Done', 'Done'), ('Waiting', 'Shipping')], default='Waiting', max_length=50),
        ),
    ]
