# Generated by Django 4.2.1 on 2023-06-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permission_remove_user_role_user_company_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role_related', related_query_name='user_role', to='user.userrole'),
        ),
    ]
