# Generated by Django 4.1.3 on 2023-04-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
