# Generated by Django 4.2.1 on 2023-07-05 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_management', '0002_remove_customer_channel_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information_management.channel', verbose_name='Channel'),
        ),
    ]
