# Generated by Django 4.1.3 on 2023-05-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_management', '0004_alter_customer_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='note',
            new_name='notes',
        ),
    ]
