# Generated by Django 4.1.3 on 2023-05-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_management', '0008_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
