# Generated by Django 4.1.3 on 2023-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_management', '0011_alter_supplier_tax_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_supplier_name_company'),
        ),
    ]
