# Generated by Django 4.1.3 on 2023-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_management', '0012_supplier_unique_supplier_name_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
