# Generated by Django 4.2.1 on 2023-07-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-timestamp'], 'verbose_name': 'History', 'verbose_name_plural': 'Histories'},
        ),
    ]
