# Generated by Django 4.2.1 on 2023-06-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Permission name')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Permission code')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Role name')),
                ('code', models.CharField(max_length=100, verbose_name='Role code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role_company_related', related_query_name='user_role_company', to='information_management.company', verbose_name='Company')),
                ('permissions', models.ManyToManyField(blank=True, to='system_admin.permission', verbose_name='Permission')),
            ],
        ),
    ]
