# Generated by Django 4.2.1 on 2023-06-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0002_alter_userrole_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='code',
            field=models.CharField(choices=[('none', 'None'), ('system_admin', 'System admin'), ('system_employee', 'System employee'), ('shipper', 'Shipper')], max_length=100, verbose_name='Role code'),
        ),
    ]
